export const ENV = {
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_API_PREFIX: process.env.NEXT_PUBLIC_API_PREFIX,
  NEXT_PUBLIC_VERSION: process.env.NEXT_PUBLIC_VERSION,
  MONGODB: process.env.MONGODB,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  CRON_SECRET: process.env.CRON_SECRET,
  BCRYPT_SALT_ROUND: process.env.BCRYPT_SALT_ROUND,
}
